title:              Mes p'tits bouquins
email:              #your-email@example.com
description:        Annotations et descriptions
author:             #Start Bootstrap
baseurl:            "/bookies/"
url:                "https://vladke99.github.io"

# Social Profiles
twitter_username:   #SBootstrap
github_username:    epfl-ada/ada-2021-project-nasa-flatpat
facebook_username:  #StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google#_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
remote_theme:       startbootstrap/startbootstrap-clean-blog-jekyll
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site


css_dir: "assets/css" # defaults to "css"
